# Generated by Django 4.0.5 on 2022-06-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicdropdown', '0002_rename_title_topic_subject_subject_subject_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_title',
            new_name='title',
        ),
    ]
